# this file is a config file. Admin only.
#name: #option
#lore: #option
#enchants: #option
#break: #option -> true or false
#flags: #option -> read JavaDoc

# --- name rule ---
# Do not use space character.
# Do not use "null" except when you want to mean "no-item".
# Do not name that the length less than 3.
# Have to use sentences.
######
base: gold_block

result-items:
  - first
  - second
result-item:
  first: # test section
    material: iron_block #need
    amount: 2 #need -> 0 < amount < common sense

  second:
    material: gold_ingot
    amount: 10

    lore:
      - line 1
      - line 2
    enchants:
      - mending,10
      - luck,2
    flags:
      - hide_dye




recipe-materials-list:
  - first
  - second

recipe-materials:
  first:
    material: coal # need
    amount: 1 # need (default:1 -> when you set this over 1, rarely occur errors.

  second:
    material: stone
    amount: 1

recipe-list:
  - stone-to-iron
  - iron-to-gold
recipes:
  stone-to-iron:
    size: 3 # 3 <= size <= 6 (int)
    result: first
    recipe:
      - second,second,second
      - second,null,second
      - second,second,second
  iron-to-gold:
    size: 4
    result: second
    recipe:
      - first,first,null,null
      - null,null,null,first
      - first,first,null,null
      - null,null,first,first