baseBlock: "plugins/Custom_Crafter/baseBlock"
results:
  - "plugins/Custom_Crafter/results"
matters:
  - "plugins/Custom_Crafter/matters"
recipes:
  - "plugins/Custom_Crafter/recipes"

permissions: "plugins/Custom_Crafter/permissions.yml"
relate: "plugins/Custom_Crafter/relate.yml"

# Reload Notice
notice:
  - "=========="
  - ""
  - "The custom crafter system was reloaded."
  - ""
  - "=========="

# Download Settings
download_threshold: 20
load_interval: 20
download:
  - ""

# DO NOT TOUCH CONTENTS THAT ARE UNDER THIS LINE.

DefinedCommands:
  args: ["-reload","-open","-show","-give","-file","-permission","-help"]

  # child: has child args
  # permission: -> List (nullable)
  # console: true or false
  # class:
  # method:
  # [args]: -> List (nullable)

  -reload:
    child: false
    # permission:
    #   - or cc.reload (and cc.reload)
    #   - or cc.op (and cc.op)
    permission: cc.reload | cc.op
    console: true
    class: com.github.sakakiaruka.customcrafter.customcrafter.command.Check
    method: reload
    descriptions:
      - When this command executing, the system save and load info from config files.

  #----------------------------------------

  -open:
    child: false
    permission: cc.op | cc.open
    console: false
    class: com.github.sakakiaruka.customcrafter.customcrafter.command.Check
    method: open

  #----------------------------------------

  -show:
    child: true
    args:
      - "-all"
      - "{Recipe}"
    permission: cc.op | cc.show
    console: true
    class: com.github.sakakiaruka.customcrafter.customcrafter.command.Show
    method:
      - all
      - one

    descriptions:
      - "0:This command shows all permissions that enabled in this server."
      - "1:This command shows the specified permission that enabled in this server."

  #----------------------------------------

  -give:
    child: true
    args:
      - "-matter,{Matter}"
      - "-result,{Result}"
    permission: cc.op | cc.give
    console: false
    class: com.github.sakakiaruka.customcrafter.customcrafter.command.Give
    method:
      - matter
      - result

  #----------------------------------------

  -file:
    child: true
    args:
      - "-make,defaultPotion"
    permission: cc.op | cc.file
    console: true
    class: com.github.sakakiaruka.customcrafter.customcrafter.command.File
    method:
      - defaultPotion

  #----------------------------------------

  -permission:
    child: true
    args:
      - "{RecipePermission}"
      - "-permissions,{Player}"
      - "-permissions,-modify,{Player},add,{RecipePermission}"
      - "-permissions,-modify,{Player},remove,{RecipePermission}"
    permission: cc.op | cc.permission
    console: true
    class: com.github.sakakiaruka.customcrafter.customcrafter.command.PermissionCheck
    method:
      - tree
      - show
      - add
      - remove

  #----------------------------------------

  -help:
    child: true
    args:
      - "-all"
      - "{CommandArgs}"
    permission: cc.op | cc.reload | cc.give | cc.permission | cc.file | cc.open
    console: true
    class: com.github.sakakiaruka.customcrafter.customcrafter.command.Help
    method:
      - all
      - one