baseBlock: "plugins/Custom_Crafter/baseBlock"
results:
  - "plugins/Custom_Crafter/results"
matters:
  - "plugins/Custom_Crafter/matters"
recipes:
  - "plugins/Custom_Crafter/recipes"

# Reload Notice
notice:
  - "=========="
  - ""
  - "The custom crafter system was reloaded."
  - ""
  - "=========="

# Download Settings
download_threshold: 20
load_interval: 20
download:
  - ""

# ParsedCommands config
commands:
  - name: give
    hasArguments: true
    arguments:
      - "-matter {Matter}"
      - "-result {Result}"

  - name: show
    hasArguments: false

  - name: reload
    hasArguments: false

  - name: open
    hasArguments: false

  - name: file
    hasArguments: true
    arguments:
      - "-make defaultPotion"

  - name: permission
    hasArguments: true
    arguments:
      - "{RecipePermission}"
      - "-permissions {Player}"
      - "-modify {Player} {add|remove} {RecipePermission}"