baseBlock: "plugins/Custom_Crafter/baseBlock"
result: "plugins/Custom_Crafter/result"
matter: "plugins/Custom_Crafter/matter"
recipes: "plugins/Custom_Crafter/recipe"

# Download Settings
download_threshold: 20
load_interval: 20
download:
  - ""