baseBlock: "plugins/Custom_Crafter/baseBlock"
results:
  - "plugins/Custom_Crafter/results"
matters:
  - "plugins/Custom_Crafter/matters"
recipes:
  - "plugins/Custom_Crafter/recipes"

# Reload Notice
notice:
  - "=========="
  - ""
  - "The custom crafter system was reloaded."
  - ""
  - "=========="

# Download Settings
download_threshold: 20
load_interval: 20
download:
  - ""

# DO NOT TOUCH CONTENTS THAT ARE UNDER THIS LINE.
# Defined Commands
DefinedCommands:
  - "-reload,false"
  - "-open,false"
  - "-show,true,1,-all"
  - "-show,true,1,{Recipe}"
  - "-give,true,2,matter,{Matter}"
  - "-give,true,2,result,{Result}"
  - "-file,true,2,-make,defaultPotion"
  - "-permission,2,true,{RecipePermission}"
  - "-permission,3,true,-permissions,{Player}"
  - "-permission,5,true,-modify,{Player},add,{RecipePermission}"
  - "-permission,5,true,-modify,{Player},remove,{RecipePermission}"
