baseBlock: "plugins/Custom_Crafter/baseBlock"
results:
  - "plugins/Custom_Crafter/results"
matters:
  - "plugins/Custom_Crafter/matters"
recipes:
  - "plugins/Custom_Crafter/recipes"

permissions: "plugins/Custom_Crafter/permissions.yml"
relate: "plugins/Custom_Crafter/relate.yml"

# Reload Notice
notice:
  - "=========="
  - ""
  - "The custom crafter system was reloaded."
  - ""
  - "=========="

# Download Settings
download_threshold: 20
load_interval: 20
download:
  - ""

# DO NOT TOUCH CONTENTS THAT ARE UNDER THIS LINE.
COMMAND_ARGS: ["reload", "open", "show", "give", "file", "permission", "help", "container"]

reload:
  - "When this command executing, the system save and load info from config files."

open:
  - "If you send this command from a console, the system cannot complete to processing this."
  - "When this command executing, the crafting gui is opened."

show:
  - "show all = This command shows all recipe info that enabled in this server. "
  - "show {RECIPE} = This command shows the specified recipe info that enabled in this server."

give:
  - "If you send this command from a console, the system cannot complete to processing this."
  - "give matter {MATTER}"
  - "    When you send this command, you can get like a specified Matter."
  - "give result {RESULT}"
  - "    When you send this command, you can get like a specified Result."

file:
  - "file make defaultPotion = When you send this command. the system makes default-potion-Matter files."

permission:
  - "permission {RECIPE_PERMISSION}"
  - "    This command shows the specified permission info."
  - "permission permissions {PLAYER}"
  - "    This command shows permissions that the specified player has."
  - "permission permissions modify {PLAYER} add {RECIPE_PERMISSION}"
  - "    This command adds the specified permission to the player has."
  - "permission permissions modify {PLAYER} remove {RECIPE_PERMISSION}"
  - "    This command removes the specified permission from the player has."

help:
  - "help all"
  - "    This command shows all commands info."
  - "help {COMMAND_ARGS}"
  - "    This command shows the specified commands info."
  - "For example, when you send '/cc help help' command, the system shows the description that above."

container:
  - "If a sender sends this command from a console, this command will not work."
  - "If a sender has not any items in their MainHand, this command will not complete to processing."
  - "container add {CONTAINER_KEY} {CONTAINER_TYPE} {CHARACTER}"
  - "    This command adds the specified data to an item that a sender has."
  - "container remove {CONTAINER_KEY} {CONTAINER_TYPE}"
  - "    This command removes the specified data from an item that a sender has."
  - "container set {CONTAINER_KEY} {CONTAINER_TYPE} {CHARACTERS}"
  - "    This command sets the specified data to an item that a sender has."
  - "container value_modify {CONTAINER_KEY} {CONTAINER_TYPE} {OPERATOR} {CONTAINER_KEY} {CHARACTERS}"
  - "    This command modifies the specified data that the specified container and keyed with a mathematical operator."
  - "container data show"
  - "    This command shows the containers info that is the sender has in their MainHand."
