name: Custom_Crafter
version: '${project.version}'
main: com.github.sakakiaruka.customcrafter.customcrafter.CustomCrafter
api-version: 1.19
authors: [ SakakiAruka ]
commands:
  cc:
    permission: cc.op

permissions:
  cc.op:
    default: op