name: Custom_Crafter
version: '${project.version}'
main: com.github.sakakiaruka.cutomcrafter.customcrafter.CustomCrafter
api-version: 1.19
authors: [ SakakiAruka ]
commands:
  cc:
    permission: cc.main

permissions:
  cc:
    default: op
