name: Custom_Crafter
version: '${project.version}'
main: com.github.sakakiaruka.customcrafter.customcrafter.CustomCrafter
api-version: 1.19
authors: [ SakakiAruka ]
softdepend: ["PlaceholderAPI"]
load: POSTWORLD
commands:
  cc:
    permission: cc.op

  history_database:
    permission: cc.op

permissions:
  cc.*:
    children:
      cc.op: true
      cc.reload: true
      cc.give: true
      cc.permission: true
      cc.file: true
      cc.craft: true
      cc.show: true
      cc.open: true

  cc.op:
    default: op
    description: Allows to send all operations.

  cc.reload:
    default: false
    description: Allows to reload config files.

  cc.give:
    default: false
    description: Allows to receive matters and results.

  cc.permission:
    default: false
    description: Allows to modify permissions.

  cc.file:
    default: false
    description: Allows to modify config files.

  cc.craft:
    default: true
    description: Allows to craft items.

  cc.show:
    default: false
    description: Allows to send commands that display recipes.

  cc.open:
    default: false
    description: Allows to open the crafting gui from the command.