name: Custom_Crafter
version: '${project.version}'
main: io.github.sakaki_aruka.customcrafter.CustomCrafter
api-version: '${paper_api.version}' #"1.21.4"
authors: [ Sakaki-Aruka ]

libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:${kotlin.version}"

commands:
  cc:
    permission: cc.command

permissions:
  cc.command:
    default: op

  cc.craftui.click.open:
    default: true

  cc.craftui.command.open:
    default: false