name: Custom_Crafter
version: '${project.version}'
main: io.github.sakaki_aruka.customcrafter.CustomCrafter
api-version: '${paper_api.version}' #"1.21.4"
authors: [ Sakaki-Aruka ]
depend:
  - MCKotlin-Paper

commands:
  cc:
    permission: cc.command

permissions:
  cc.command:
    default: op