name: PaperMC Plugin Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build plugin with Maven
        run: mvn clean package

      - name: Create server directory
        run: mkdir server

      - name: Download PaperMC 1.21.3
        working-directory: ./server
        run: wget https://api.papermc.io/v2/projects/paper/versions/1.21.3/builds/83/downloads/paper-1.21.3-83.jar -O paper.jar

      - name: Accept EULA
        working-directory: ./server
        run: echo "eula=true" > eula.txt

      - name: Create plugins directory and copy plugin
        working-directory: ./server
        run: |
          mkdir plugins
          cp ../target/*.jar ./plugins/

      - name: Run PaperMC server and wait for plugin to shut it down
        working-directory: ./server
        env:
          PLATFORM: "github-actions" # 環境変数を設定
        run: |
          echo "Starting PaperMC server for plugin tests..."
          java -Xms1G -Xmx1G -jar paper.jar nogui
          echo "PaperMC server process ended."

      - name: Evaluate test results
        working-directory: ./server
        run: |
          TEST_RESULTS_FILE="plugin-test-results.txt"
          if [ ! -f "$TEST_RESULTS_FILE" ]; then
            echo "Error: Test results file '$TEST_RESULTS_FILE' not found. This indicates the plugin test did not run or output correctly."
            exit 1 
          fi

          echo "Content of $TEST_RESULTS_FILE:"
          cat "$TEST_RESULTS_FILE"
          echo "--- End of $TEST_RESULTS_FILE ---"

          if grep -q "Failed" "$TEST_RESULTS_FILE"; then
            echo "Tests FAILED: The word 'Failed' was found in '$TEST_RESULTS_FILE'."
            exit 1 
          else
            echo "Tests PASSED: The word 'Failed' was NOT found in '$TEST_RESULTS_FILE'."
          fi
